spring:
  application:
    name: springboot-docker-demo-prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis: 
    host: 127.0.0.1
    port: 6379
    timeout: 60000
    pool:
      max-idel: 8
      min-idel: 0
      max-active: 10
      max-wait: 600
  jps.showsql: true
mybatis:
  type-aliases-package: com.dwring.springboot.model
  mapper-locations: classpath:mapper/*.xml
  mappers: com.dwring.springboot.util.MyMapper
  mapper:
    not-empty: false
    identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    tk:
      mybatis: TRACE