package com.qf.springboot.mapper;

import com.qf.springboot.model.UserInfo;
import java.util.List;

/**  
* @ClassName: UserInfoMapper  
* @Description:  
* @author haichangzhang  
* @date 2017年7月26日 下午6:07:04  
*    
*/
public interface UserInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbggenerated Thu May 25 16:18:06 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbggenerated Thu May 25 16:18:06 CST 2017
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbggenerated Thu May 25 16:18:06 CST 2017
	 */
	UserInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbggenerated Thu May 25 16:18:06 CST 2017
	 */
	List<UserInfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbggenerated Thu May 25 16:18:06 CST 2017
	 */
	int updateByPrimaryKey(UserInfo record);
}