server.port: 9090

#kafka
# 指定kafka 代理地址，可以多个
spring.kafka.bootstrap-servers: 47.106.217.33:9092
# 指定默认消费者group id
spring.kafka.consumer.group-id: myGroup
# 指定默认topic id
spring.kafka.template.default-topic: test1
# 指定listener 容器中的线程数，用于提高并发量
spring.kafka.listener.concurrency: 3
# 每次批量发送消息的数量
spring.kafka.producer.batch-size: 10